server:
  port: 8189
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=cosmo_schema
